### ISSUE TITLE
It seems like stylix and niri-flake not doing well

### ISSUE THREAD

**Issue by LennyLizowzskiy** [sodiboo/niri-flake#135]
```
error: The option `home-manager.users.lennylizowzskiy.programs.niri.finalConfig' in `/nix/store/a7idmrymwccm7gnssm2hb04f6yk2mz9c-source/nixos/common.nix' is already declared in `/nix/store/hixvzv8fr9k5dp9fvrxyhjvij9f6r84p-hx7fxaip5vqk92y05rjsyf25hfb5vhph-source/home-manager/presets/per-user/lennylizowzskiy/configs/gui/de/niri'.
```

Config:
```
# home-manager
{
  imports = [
    inputs.niri-flake.homeModules.config

    # ...
  ];

  home.packages = with pkgs; [
    # ...
  ];

  programs.niri = {
    settings = {
      prefer-no-csd = true;

      output = {
        "DP-2".mode = "2560x1440@142.000";
      };
  # ...
```

I'm running NixOS unstable with stylix and home-manager both enabled

**Comment by sodiboo** [comment]
Are you installing both the NixOS and home-manager modules? My NixOS module will automatically add the home-manager module (and stylix module), and this option looks like a duplicate definition (i.e. imported by my module, and by you separately in the 4th line of the snippet you posted)

**Comment by LennyLizowzskiy** [comment]
Here's how I installed niri:

NixOS: https://github.com/LennyLizowzskiy/nix-config/blob/master/nixos/presets/per-machine/_shared/specifics/de/niri-full.nix

home-manager: https://github.com/LennyLizowzskiy/nix-config/blob/master/home-manager/presets/per-user/lennylizowzskiy/configs/gui/de/niri/default.nix

Are there any problems?

**Comment by LennyLizowzskiy** [comment]
Oh, I get what you said. I should try installing without importing the home-manager module. Let me try it

**Comment by LennyLizowzskiy** [comment]
Now it seems like I misunderstood how your module converts Nix to KDL

```
error: The option `home-manager.users.lennylizowzskiy.programs.niri.settings.output' does not exist. Definition values:
       - In `/nix/store/8c08xfcqrz2rrkryxhj3hz17ab3agrzi-h1kjhg6176q9y7zymyi4cq9k1ki83p0k-source/home-manager/presets/per-user/lennylizowzskiy/configs/gui/de/niri':
           {
             eDP-1 = {
               mode = "2560x1600@60.001";
             };
           }
```

**Comment by sodiboo** [comment]
> `error: The option `programs.niri.settings.output' does not exist.`

To directly use a "kdl-equivalent" config, please set `programs.niri.config`. This can either be a string literal (config file contents), or a kdl document as defined in the [`kdl.nix`](https://github.com/sodiboo/niri-flake/blob/main/kdl.nix) file in this repository. For an example on how to use that, see [`default-config.kdl.nix`](https://github.com/sodiboo/niri-flake/blob/main/default-config.kdl.nix) which is translated from the default config in niri a while back.

`programs.niri.settings` is *not* just a "translated from nix to kdl" because they are fundamentally different object models, it's not really possible (`kdl.nix` relies on extensive usage of arrays, which is annoying for large nix configs). instead, it's an entirely separate settings interface that is translated to niri's configuration format.

the key to configure monitors is `outputs` (notice the *plural*). you can view the documentation for `programs.niri.settings` in [`docs.md`](https://github.com/sodiboo/niri-flake/blob/main/default-config.kdl.nix)

**Comment by sodiboo** [comment]
Did you end up getting it working? If so, you can close this issue. Otherwise, i may do it considering i haven't heard back from you for a couple days.

**Comment by LennyLizowzskiy** [comment]
I wanted to give niri a second go but didn't do it in the end. Maybe some time later. I will reopen this issue or create a new one if I will encounter any problems again
