### ISSUE TITLE
Question: Why is this not merged with the main repo?

### ISSUE THREAD

**Issue by purrpurrn** [sodiboo/niri-flake#177]
Why hasn't this repository been merged with the main one that contains the source code? Keeping the repositories separate makes it more difficult to find. All nix modules, with the exception of `flake.nix` and `flake.lock`, could be moved to a `nix` directory.

**Comment by sodiboo** [comment]
The main reason for this is that YaLTeR, the main developer of niri, does not use nix and can't easily fix/modify a nix flake in case it breaks.

Essentially, it allows me to be more "sovereign" in a sense, being able to add new functionality and settings and refactors and such without needing to go through PRs on the main niri repo, and it allows the main niri repo to operate mostly independently of nix, knowing i'll be able to deal with it at some point but not needing to leave the main repo in a "broken" state (and also not needing to block changes to niri due to nix requirements).

(one could argue that both of these could be kind of "nullified" by giving me write access to the main niri repository; but that only creates security risks with no real benefits compared to keeping them separated. see also: xz)

---

I don't think it's necessarily more difficult to find. It's mentioned in the very first paragraph of the wiki's starting page: https://github.com/YaLTeR/niri/wiki/Getting-Started

---

This was previously discussed in various places; the most easily referenced is https://github.com/sodiboo/niri-flake/issues/7#issuecomment-1945502288.

I asked:

> Would you prefer [the binary cache to] be implemented in upstream niri [such that you control the authenticity of it]? At that point, i think it would be reasonable to move the whole module into upstream niri as well, and deprecate this repo.

To which YaLTeR says:

> I'd prefer it to be separate, I think it's better to keep nix concerns to a separate nix repo, they can be addressed quickly and without dragging away focus in the main repo issues.

And i think that's reasonable. I agree with his opinion on this issue.

---

A technical reason why we don't merge the repos is because i want to support stable niri as well. Due to being the actual system compositor, niri is inherently tied to the system's version of mesa, so whenever nixpkgs updates mesa, niri must be updated alongside it (else it will fail to display anything). On the main niri branch, this isn't problematic; we would simply update the lockfile frequently.

But that doesn't work for tagged versions, because tags inherently refer to an older commit, with an outdated lockfile. You can't have them update mesa, because they're immutable. You could override the dependencies in the system module (as this repo actually does do), but then you would not be benefiting from a binary cache (as your local closure no longer matches the one in the main repo's cache).

In this repo, there is no separation of branches/tags. There is just a `niri-stable` and `niri-unstable` input that pull commits from different points in time (and the binary cache for both are handled together)

---

cc @YaLTeR: do you have anything to add??

**Comment by YaLTeR** [comment]
This is pretty spot-on. The flake here has been enjoying rapid updates and development thanks to being separate.
