### ISSUE TITLE
add a NixOS module to nixpkgs

### ISSUE THREAD

**Issue by Schweber** [sodiboo/niri-flake#325]
First of all, thank you for your work and effort on this!

So far i haven't used flakes and am thus a bit hesitant about it. That's why i am wondering why you havent't added a `niri` module to NixOS (like the one for [hyprland](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/programs/wayland/hyprland.nix) for example)? 

I understand that using your flake provides more flexibility but i don't need that and would be happy with a "vanilla" module.

Would you consider adding one (while continuing your flake of course)?

**Comment by sodiboo** [comment]
honestly there's no real reason i haven't done that. i just never got around to it because i didn't need it, using my own repo for the module.

if you want something right now, you could just copy [the relevant options](https://github.com/sodiboo/niri-flake/blob/7ece9ac0fd48575a4f5a52ec6b9252720563cde8/flake.nix#L444-L491) into your configuration. just replace `cfg.package` with `pkgs.niri` and you'll be good to go.

i'll see what i can do about adding a niri module to nixpkgs, it is some sort of long-term goal, but as i said, i just never got around to it. but with someone wanting that now, there is at least a good reason to stop procrastinating on it

**Comment by jonvemo** [comment]
Please Add It! I'm waiting for :smile_cat:

**Comment by ocharles** [comment]
I personally think the flake is much better - it lets @sodiboo iterate much more rapidly

**Comment by sodiboo** [comment]
- https://github.com/NixOS/nixpkgs/pull/348193

that PR ^ was just merged, so i'd consider this as done. [It'll make it into `nixos-unstable` soon enough](https://nixpk.gs/pr-tracker.html?pr=348193) (and it's also going to be part of the upcoming `nixos-24.11`), and after that point i'll provide a new module from this flake that builds on top of the upstream module.

If you use my NixOS module already, you will have to remove it to make use of the one in nixpkgs. They conflict with one another, so my module disables theirs. There isn't much immediate benefit to doing so, and as such i wouldn't necessarily recommend anyone do this yet, but if you do want to use that one you also have to remove this one first. Check out the implementation differences if you want to swap, because that module isn't just a clone of this one and you should verify that switching won't remove something you were relying on.

if you don't use my flake's modules, then go ahead and test the one from nixpkgs. previous paragraph doesn't apply to you, go wild lol.
