### ISSUE TITLE
issue running xwayland-satellite: No such file or directory

### ISSUE THREAD

**Issue by KiaraGrouwstra** [sodiboo/niri-flake#343]
going by https://github.com/sodiboo/niri-flake/commit/1944dcb497ca7d78a43d98258bbc45c1706f2919, i tried [installing `xwayland-satellite`](https://codeberg.org/kiara/cfg/commit/961cb58793f10baf4a1edd17d89b4cd8e747ef26).
as per https://github.com/Supreeeme/xwayland-satellite?tab=readme-ov-file#usage and https://github.com/YaLTeR/niri/wiki/Xwayland#using-xwayland-satellite, it seems invoking it should be a matter of just running `xwayland-satellite`, but that seemed to get me an error as follows:
> thread 'main' panicked at /source/src/lib.rs:80:10:
> called `Result::unwrap()` on an `Err` value: Os { code: 2, kind:
NotFound, message: "No such file or directory" }

(`RUST_BACKTRACE=1 xwayland-satellite` appeared to not actually yield a stack trace.)

before diffing nixpkgs versions and the like, this does seem to be how the package would be invoked, right?

**Comment by sodiboo** [comment]
Do you also have Xwayland installed? The package i provide is *not* very robust, and i believe it relies on Xwayland being in the system path. This shouldn't be how it works ideally, but it is how it currently works because i have not done much work besides making it build and sharing that with others.
