### ISSUE TITLE
Niri Nixpkgs may need to be equal to NixOS Nixpkgs

### ISSUE THREAD

**Issue by Kha** [sodiboo/niri-flake#4]
I got a black screen without error output until adding this line, worth pointing out in the readme?
```
    niri.inputs.nixpkgs.follows = "nixpkgs";
```

**Comment by sodiboo** [comment]
I don't do this, and my system has worked fine. Do you know if there's a particular package that must be in sync? I don't see any reason why it should be necessary.

**Comment by Kha** [comment]
Yeah, I was confused by it as well to be honest but it definitely fixed the issue for me. Among multiple tries I *once* get an error `libGL error: DRI driver not from this Mesa build` that made me try this, other than that I have no idea what could be going wrong.

**Comment by sodiboo** [comment]
The exported `packages.${system}.niri` now has an overridable property `pkgs` which can be used to set all native dependencies. In the NixOS module, it will automatically override to use the `pkgs` provided by the configuration, instead of the flake inputs. This means niri will always compile against the same version of mesa as in your system `pkgs`, and you no longer need to override the `nixpkgs` input. https://github.com/sodiboo/niri-flake/commit/dd8755d42d3854fc0c60e99eccd16a4c3dd282ec?diff=unified&w=1

**Comment by Kha** [comment]
Thanks!
