### ISSUE TITLE
"switch-events" support

### ISSUE THREAD

**Issue by Titaniumtown** [sodiboo/niri-flake#591]
I noticed that it seems this flake does not have support for the [switch-events](https://github.com/YaLTeR/niri/wiki/Configuration:-Switch-Events) config section. Could this be added?

Example usage:
```nix
      switch-events = with config.lib.niri.actions; {
        "lid-close" = spawn [ "${pkgs.swaylock}/bin/swaylock"];
      };
```

**Comment by sodiboo** [comment]
Yes, this will be added. I just didn't get around to it yet. Feel free to open a PR adding it, else I'll implement it at some point. Maybe later today, now that I was reminded of it (I may have nearly forgot in general)

**Comment by Titaniumtown** [comment]
@sodiboo I'll have to read through the flake, if I have time I'll open a PR. Thanks!

**Comment by Titaniumtown** [comment]
> @sodiboo I'll have to read through the flake, if I have time I'll open a PR. Thanks!

ahah I have no idea how to add it :p srry

**Comment by sodiboo** [comment]
implemented in https://github.com/sodiboo/niri-flake/commit/00f14d334c81ad79417de78e5b38ec35a2f5f658

you can use the example snippet posted above in your initial issue body with one small modification

```diff
      switch-events = with config.lib.niri.actions; {
-       "lid-close"        = spawn [ "${pkgs.swaylock}/bin/swaylock"];
+       "lid-close".action = spawn [ "${pkgs.swaylock}/bin/swaylock"];
      };
```

this is for forward-compatibility if/when additional props are added to switch events.

also note that `config.lib.niri.actions` contains a bunch of functions that aren't allowed here, only `spawn` is legal. however, since both this and other `binds` have the same shape, the spawn function provided by `lib.niri.actions` will work fine. it's "Technically Wrong", though. see [docs](https://github.com/sodiboo/niri-flake/blob/main/docs.md#switch-bindaction) for "correct" usage.

**Comment by Titaniumtown** [comment]
fantastic! thanks so much
