### ISSUE TITLE
Feature request: Support setting an output to "off" while keeping its other options

### ISSUE THREAD

**Issue by ViciousBadger** [sodiboo/niri-flake#660]
Hello! First of all thanks for this amazing flake.

I have a multi-monitor setup, but only ever use one monitor at a time (TV or desktop essentially).
The TV needs to be scaled up in order to be usable, but at the same time turned off (in niri) until I manually turn it on.

I tried the following: 
```
"HDMI-A-1" = {
  enable = false;
  scale = 1.5;
};
```
.. which generates this line of configuration:
```
output "HDMI-A-1" { off; }
```
.. and it turns the TV off as expected, but the `scale` option is ignored.

I'm not sure if it would be idiomatic nix to keep the other options if `enabled` is set to false, but it would solve my issue. Alternatively, we could have a separate option for setting the `off` flag.. which would look a bit odd..

**Comment by sodiboo** [comment]
honestly same. like, I want an identical thing to you. I just let it be enabled and manually disable it when starting a session lol. 

I'll try to implement this later today, since apparently I'm not the only one getting annoyed by it. I'm pretty sure it's not idiomatic nix, but honestly idiomatic nix is very ill-defined and not necessarily something to strive for, especially in this case where the usability of the module should clearly be prioritized first.

**Comment by sodiboo** [comment]
https://github.com/sodiboo/niri-flake/commit/7a05cfa196225335374283f1bc7bee1826164a72

**Comment by ViciousBadger** [comment]
It works ✨flawlessly✨. Thank you!!!

**Comment by sodiboo** [comment]
yay!
